### PR TITLE
FEAT-127: implementation of scheduling api

### PR DESCRIPTION
**Pull request by phong1233**
# Description

implement scheduling routes

Issue reference: #127 

## Type of change

Please delete options that are not relevant.

- [ ] BUG (Fixing or documenting a bug)
- [x] FEAT (Add a new feature to the project)
- [ ] CHORE (Something that needs to be done outside of the issue)
- [ ] DOCS (Implement documentation)
- [ ] TASK (A task that must be done to complete an issue)

# Checklist:

- [x] My pull request references the issue in the comments
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Talos10** [comment]
PR looks great! One thing is that we'll have to merge my PR first and then resolve some conflicts on this one before you can merge it. Also, once my PR is merged, you could update docs for the routes files with the new routes you created. @N0ot-No0t also wants to add more customers to the db when it loads up so we can add them to your PR once my is merged.

**Review by sebastien-blain — COMMENTED** [review]
I see you update an order to 'in progress' when you schedule a machine for it. 
Does that mean we should remove the ability to change the status of an order from the manufacturing tab? In doing so, the only way to start an order would be to schedule a machine for it. 

The same is applicable to finish an order. If we free a machine, does this mean the order is completed? If yes, then we should remove the buttons in the frontend to change the state of a manufacturing order to 'in progress' and 'completed'.

Maybe only the raw materials don't need to be scheduled in that case.

**Comment by phong1233** [comment]
> I see you update an order to 'in progress' when you schedule a machine for it.
> Does that mean we should remove the ability to change the status of an order from the manufacturing tab? In doing so, the only way to start an order would be to schedule a machine for it.
> 
> The same is applicable to finish an order. If we free a machine, does this mean the order is completed? If yes, then we should remove the buttons in the frontend to change the state of a manufacturing order to 'in progress' and 'completed'.
> 
> Maybe only the raw materials don't need to be scheduled in that case.

Yes we should do that when we will work on the frontend

**Review by Talos10 — APPROVED** [review]
Looks great!

**Review by sebastien-blain — APPROVED** [review]

**Pull request merged**
