### PR TITLE
Planning page frontend (implemented routes)

### LINKED ISSUE #66: [Front-end] Implement Planning Page
## Description
As a user, I want to be able to plan events and company goals.

### Overview
When the user access the Planning Page, they will have access to a list of upcoming company events as well as a list of goals that should be achieved by a given date (i.e. build X amount of bikes, make X amount in profit, ...) 

Create Planning Page:

1) Events Table
- date
- time
- description

2) Goals Table
- Checkbox to mark as completed
- Target Date
- description

3) Add Event Form
- On click of a button, user will be redirected to a form where they can create a new event

4) Add Goal Form
- On click of a button, user will be redirected to a form where they can create a new goal

### Acceptance criteria
- [ ] Unit-tests are passing
- [ ] Planning page showcases an Events and a Goals table
- [ ] The goals can be marked as complete
- [ ] User can access a form to add an event
- [ ] User can access a form to add a goal

### PR DESCRIPTION
**Pull request by d-rossi**
# Description
Implemented routes for the events and goals of the planning page.
- Retrieval of events and goals
- Deletion of events and goals
- Add events and goals
- Update completion status of a goal

Issue reference: #66 

## Type of change

- [ ] BUG (Fixing or documenting a bug)
- [ ] FEAT (Add a new feature to the project)
- [ ] CHORE (Something that needs to be done outside of the issue)
- [ ] DOCS (Implement documentation)
- [x] TASK (A task that must be done to complete an issue)

# Checklist:

- [x] My pull request references the issue in the comments
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by phong1233 — APPROVED** [review]
noice

**Review by sebastien-blain — COMMENTED** [review]
Can we remove an occurrence of the save button. I think we should only have 1.
image
image

**Comment by sebastien-blain** [comment]
Can you also extend the line of the header so it takes the full length. Same for the goals. Thanks
image

**Comment by sebastien-blain** [comment]
And can we make it so we can delete goals even once they are finished. This would also solve your missing line.
image

**Comment by PatrickYoussef** [comment]
> And can we make it so we can delete goals even once they are finished. This would also solve your missing line.
> image

**Review by sebastien-blain — APPROVED** [review]
Nice changes

**Pull request merged**
