### PR TITLE
Feat 77/customer sales page

### PR DESCRIPTION
**Pull request by N0ot-No0t**
# Description

Added a page to see all available customers and to be able to add more to the list.

Issue reference: #77

## Branch and Commit name must follow this template
```
Branch template: {ISSUE TYPE}-{Issue number}/{desciption_of_branch}
Commit template: {ISSUE TYPE}-{Issue number}: {description of changes}
```

## Type of change

Please delete options that are not relevant.

- [ ] BUG (Fixing or documenting a bug)
- [x] FEAT (Add a new feature to the project)
- [ ] CHORE (Something that needs to be done outside of the issue)
- [ ] DOCS (Implement documentation)
- [ ] TASK (A task that must be done to complete an issue)

# Checklist:

- [x] My pull request references the issue in the comments
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sebastien-blain** [comment]
Nice, can you fix a few things:
On the customer page, change the font of your table's header to match the one on the other tables.
And make the search bar take the full width of the table.
And remove the cursor pointer on the table because we cant click.
image

And can you put some space between the 2 text inputs and put the add customer button at the top, this format is used in all our forms.
image

And finally, just fix all the warnings, otherwise, the GitHub action doesn't pass.
image

**Comment by N0ot-No0t** [comment]
I addressed your issues @sebastien-blain, except the search bar. I tried a full length search bar at the beginning and it looked ugly so this is why I settled with the current search bar. Also, the "material-ui" library makes the mouse cursor display in that fashion when it hovers over the table body (as opposed to the table head).

**Comment by sebastien-blain** [comment]
@N0ot-No0t Good, ok for the search bar.

About the table header, the color is still not the same:
image

We want:
image

I don't know what the style is but I'm sure you can figure it out 😀

**Comment by N0ot-No0t** [comment]
> @N0ot-No0t Good, ok for the search bar.
> 
> About the table header, the color is still not the same:
> image
> 
> We want:
> image
> 
> I don't know what the style is but I'm sure you can figure it out 😀

Sorry I thought you meant to remove the boldness of the header. Is this what you want?

image

**Comment by sebastien-blain** [comment]
@N0ot-No0t Yeah looks good, if it's the same as the other, it's good.

**Review by sebastien-blain — APPROVED** [review]
Looks good

**Review by phong1233 — APPROVED** [review]

**Pull request merged**
