### PR TITLE
CHORE-82: Removed naming check on merge pull request

### PR DESCRIPTION
**Pull request by sebastien-blain**
# Description

Brief summary of the changes made.

Issue reference: #{Insert issue number here}

## Branch and Commit name must follow this template
```
Branch template: {ISSUE TYPE}-{Issue number}/{desciption_of_branch}
Commit template: {ISSUE TYPE}-{Issue number}: {description of changes}
```

## Type of change

Please delete options that are not relevant.

- [ ] BUG (Fixing or documenting a bug)
- [ ] FEAT (Add a new feature to the project)
- [x] CHORE (Something that needs to be done outside of the issue)
- [ ] DOCS (Implement documentation)
- [ ] TASK (A task that must be done to complete an issue)

# Checklist:

- [x] My pull request references the issue in the comments
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Talos10 — APPROVED** [review]
End the dictatorship!

**Review by phong1233 — CHANGES_REQUESTED** [review]
It doesn't work like that @sebastien-blain . Each step requires the previous if you put an if statement then nothing runs

**Comment by sebastien-blain** [comment]
> It doesn't work like that @sebastien-blain . Each step requires the previous if you put an if statement then nothing runs

Ok then lets remove the needs

**Review by N0ot-No0t — APPROVED** [review]

**Review by phong1233 — DISMISSED** [review]
I don't want to deploy if test don't pass

**Comment by sebastien-blain** [comment]
@phong1233 The checking once a pr is merged is useless because the pr needs to pass all before being merged.

**Comment by phong1233** [comment]
> @phong1233 The checking once a pr is merged is useless because the pr needs to pass all before being merged.

Testing when integrating and deploying is actually the most important part

**Review by phong1233 — CHANGES_REQUESTED** [review]
Terrible

**Review by phong1233 — DISMISSED** [review]
this is worst why are we testing in linting phase

**Pull request merged**
