### PR TITLE
Clean up frontend, small fixes and refactors.

### LINKED ISSUE #98: SideNav Not Updating Properly When Changing Account.
The side bar does not update on changes done to in children components. As such, when an admin user logs out and logs back in with an employee account, the admin tab is still visible even though an employee should not see it. To circumvent this issue, a temporary fix was made that refreshes the web page to allow the SideNav component to reload.

[To be resolved for next sprint]

### LINKED ISSUE #100: Be able to delete users in admin page

### LINKED ISSUE #102: Admin page user list component doesn't update when adding a new user to the list.
When the admin creates a new user using the frontend, the new user is added to the database using the backend, but the list itself doesn't update. As a temporary fix for this issue, the page is refreshed to reload the components present on the page and display the new user.

### PR DESCRIPTION
**Pull request by tjosepo**
# Description

This PR consists of small fixes and refactors for the frontend.

These changes include:

- Resolved warning messages when building the app.
- Removed code that would make the page reload.
- Changed the visuals of the Admin page to make it match the mockups.
- Added a "Remove" option to the role selector.
- Used Snackbars to notify the user when users where added, modified, and deleted.
- Changed the export and import buttons of the Inventory page from ``variant="contained"`` to ``variant="outlined"``.
- Used Snackbars to notify the user when the import was successful.
- Fixed outline of the Recipe input on the Add Item page.
- Added the "className" and "title" props to the Container component and adjusted existing pages to use these props.
- Added an active state to the sidenav links and used Material-UI buttons.
- Added a background color to the Login page in case the background image didn't load.
- Made the "Forgot Password?" text from the Login page vertically aligned with the "Log In" button.

Resolves #98 , resolves #100 , resolves #102.

### Admin
image

## Type of change

- [X] CHORE (Something that needs to be done outside of the issue)

# Checklist:

- [X] My pull request references the issue in the comments
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tjosepo** [comment]
btw, this is a thing.
image

Tell me if you think it needs fixing.

**Review by Talos10 — APPROVED** [review]
Looks good!

**Review by sebastien-blain — COMMENTED** [review]
Nice changes.

I noticed the menu for the recipe doesn't allow the user to type words to narrow the ingredients available to create an item. Do you think it would be possible to add that functionality?
image
image

If we could narrow the list we have, it would be much easier to find the items we need and not have an extremely long list

**Comment by tjosepo** [comment]
@sebastien-blain You've insisted enough about this feature that I'll start looking into it. I also agree that it would be a good quality of life improvement for the user. If you want, you can merge this and I'll make a new PR with the changes.

**Review by sebastien-blain — APPROVED** [review]
@tommy-josepovic Hahaha, it is not a priority though. I will create a bug for it and if we have time, we could implement it.

**Pull request merged**
